### ISSUE TITLE
Create a configuration file for the NRE Labs courses

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote#10]
The web front end should pull the course list from a configuration file, and Syringe should also use this to load the courses it knows about, so that when it loads labs, associated with lessons it can also check that a known course has been specified.

This way folks aren't contributing/testing new lessons/labs that aren't in pre-existing courses, and we can easily catch when someone tries to add a course.

**Comment by Mierdin** [comment]
This has been implemented in Syringe. On initial load, Syringe will load all syringe YAML files it sees in the configured lesson directory, and once started, all of these lessons' details are available via [API](https://github.com/nre-learning/syringe/blob/master/api/exp/definitions/lessondef.proto). The front-end uses this endpoint when it loads the page to populate the menu structure dynamically. So as long as the Syringe instance knows what the lessons are, it will stem out from there.
