### ISSUE TITLE
New Lesson - Robot Framework

### ISSUE THREAD

**Issue by saimkhan92** [nre-learning/antidote#112]
@lara29  and I are planning to contribute a tutorial(primer) on the Robot Framework(wrt automated network verification). Please let us know if the tutorial outline seems appropriate. 

@Mierdin @cloudtoad @jameskellynet 

##### Chapter 1
- Introduction
- Installation
- Types of libraries/keywords
- Robot file format/syntax (introduction)
- Basic Example 1 (without vSRX interaction)
	
##### Chapter 2
- Project organization/directory structure
- Robot file format/syntax (continued)
- Basic example 2 (with vSRX interaction)
	
##### Chapter 3
- Tags/Setup/teardown
- Detailed example3 + Explanation (with vSRX interaction)

**Comment by Mierdin** [comment]
@saimkhan92 @lara29 This looks great. 👍 Chapter 2 and 3 are a little light on description but I think this is a good start and we can iterate on the pull request.

Have fun, and let us know if you need anything to keep moving.

**Comment by lara29** [comment]
Thanks @Mierdin 
We'll add more sub-topics into chapter 2&3 once we have completed with the basic layout.

**Comment by saimkhan92** [comment]
# <center>Detailed Project Outline</center>

## <center>Chapter 1</center>

* Introduction
    - written in python
    - used for acceptance testing
    - keyword driven
* Types of keywords
    - built-in, standard libnrary, external libraries, private library
* Rules and Syntax 
    - cell spacing, 4 tables
    - variable declaration(scalar, lists, dictionaries)
* Explain 4 tables
    - settings, variables, keywords, testcases
* Example1
    - basic syntax demo
    - import a simple private library
    - demo variables, settings, testcases (tables)
    - demo scalar variable
    - define multiple testcases in a testsuite
    - use built-in and library keywords
    - demo running a robot testsuite
    - demo a failure case


## <center>Chapter 2</center>
* Topology information vSRX
    - hostname: "vsrx-robot"
    - model: "VSRX"
* Explain private library functions
* Example1
    - use keywords from junos private library
    - passing variables from the command line, parsing them inside the robot file
    - passing arguments for private functions/keywords

## <center>Chapter 3</center>
* Demo user defined keywords
* Create a separate resource file and demonstrate importing it
* Project organization, directory structure best practices
    - data, libraries, resources, results, tests
* Example1
    - demo user defined keywords
    - demo FOR loop for parsing a returned dictionary
    - demo logging
* Example2
    - test setup/teardown
    - import resource file

**Comment by jameskellynet** [comment]
I can't wait to try this lesson and learn this stuff. Great stuff!

**Comment by Mierdin** [comment]
Doesn't matter for now, pick one that's unique and we will make sure it's still unique before merge to master of this repo if applicable

**Comment by lara29** [comment]
Okay, we'll do that, thanks!

**Comment by Mierdin** [comment]
Utility container is fine.

**Comment by lara29** [comment]
Thanks!

**Comment by lara29** [comment]
@Mierdin I do not have push permission for the linux utility container. Is it possible you could add the package "robotframework" to the requirements.txt, so that I can use it for testing. Thanks!

**Comment by Mierdin** [comment]
You don't need to push it, you can add it to requirements.txt in this PR.

**Comment by Mierdin** [comment]
Closed in #125
