### ISSUE TITLE
Lesson on automating with Ansible

### ISSUE THREAD

**Issue by dgjnpr** [nre-learning/antidote#152]
Hi,

I propose a 3 stage lab.

1. Initial playbook that enables netconf on all the network
2. A playbook that creates a csv of data about all devices in a network using facts
3. How to use inventory groups to run tests only on devices in that group

Let me know what you think. Happy to tweak if necessary.

My thinking is to move away from the usual "do config with Ansible" and show how to use Ansible to your advantage.

-- 
Cheers
Dg

**Comment by Mierdin** [comment]
Trying to condense a few duplicate issues, and this one has a significant amount of overlap with https://github.com/nre-learning/antidote/issues/97.

I'll close this for now, I'd recommend chiming in on that issue with this idea, as I don't think any progress has been made over there just yet.
