### ISSUE TITLE
Syringe pod in CrashLoopBackOff state

### ISSUE THREAD

**Issue by lara29** [nre-learning/antidote#157]
Upon running ./anti-up.sh, the syringe pod is seen to be in CrashLoopBackOff state

lrajan$ kubectl get pods
NAME                                       READY   STATUS             RESTARTS   AGE
antidote-web                               2/2     Running            0          2h
nginx-ingress-controller-b685f5586-7hj25   1/1     Running            0          2h
syringe-74bd67cf64-fh7z9                   0/1     CrashLoopBackOff   33         2h

lrajan$ kubectl logs syringe-74bd67cf64-fh7z9
time="2018-10-22T20:59:21Z" level=error msg="SYRINGE_TIER is a required variable."
time="2018-10-22T20:59:21Z" level=fatal msg="Invalid configuration. Please re-run Syringe with appropriate env variables"

**Comment by Mierdin** [comment]
I updated the docs in #160 - hopefully this looks a little better and makes configuring Syringe more obvious.

https://antidoteproject.readthedocs.io/en/latest/platform/syringe/configuration.html
