### ISSUE TITLE
Lessons on automating with JET

### ISSUE THREAD

**Issue by valjeanchan** [nre-learning/antidote#164]
Hi,

I am thinking of the a 5-stage lesson for a offbox JET automation (easier to troubleshoot than onbox)
- Stage 1 would be JET rpc/notification configuration on the box and do some show command for checking
- Stage 2 receive event from notification service using mqtt client / python client say interface event / rpm events
- Stage 3 GRPC basics, IDL compilation and basic GRPC JET testing
- Stage 4 JET Firewall API acl creation / update
- Stage 5 Close loop automation - GRPC call based on MQTT events.

Any thoughts?

tonychan@jnpr

**Comment by Mierdin** [comment]
Hey @valjeanchan - looks like https://github.com/nre-learning/antidote/pull/173 was recently opened and addresses some of these. I would suggest you take a peek over there and ask @jnpr-raylam if this is something you two can collaborate on.

**Comment by valjeanchan** [comment]
Hi Matt,

Raymond and I works together on this. I think he just submitted a duplicate issue. We should have submitted a pull request on this JET lesson. 

Regards
Tony Chan
