### ISSUE TITLE
Lessons on automating with Openconfig

### ISSUE THREAD

**Issue by valjeanchan** [nre-learning/antidote#165]
Hi,

I am thinking of the a 5-stage lesson for a Openconfig and custom Yang automation

- Stage 1 install OC Yang on Junos box and provision OC config using CLI
- Stage 2 provision OC config using netconf / ansible to show it works exactly as standard junos config
- Stage 3 Custom Yang modules (service based e.g. l2service) and custom yang translator
- Stage 4 Custom Yang config provisioning using CLI and netconf
- Stage 5 Verification and Troubleshooting (show commands , logs, etc)

This is targeting beginner - immediate level users. Comments are welcomed.

tonychan@jnpr

**Comment by Mierdin** [comment]
@valjeanchan Looks good to me. Let me know when you have a PR for review, and if there's anything I can do to help.
