### ISSUE TITLE
Create the Lab template

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote#2]
We need a lab template written by lesson contributors and consumed by Syringe, so that contributors don't need to understand the inner-workings of Antidote and its components.

Templates will take certain documented node types like:
 - vJunos (a Junos VM in a container)
 - Linux black-box (contributor configured container without a terminal)
 - Linux box with terminal (guacamole session and tab for the node)
 - Jupyter (the lab's notebook)

...this can be extended in the future of course

and need to take in a lesson guide (text) to get converted to HTML in the right pane of the NRE Labs lab step. We'll need to decide what is optional and what is mandatory and the max count for types in this first incarnation of the template.

We will need a way to associate Lab templates into Lessons and into Course topics.

The networking piece is one that requires some addition detail. We need to be able to specify either a) to use the read-only singleton node, or b) some kind of topology to start in Antidote. In the case of a topology we need to know the nodes and edges to create and the default config for them.

**Comment by Mierdin** [comment]
This is done in Syringe.
