### ISSUE TITLE
Explain the project networking in the docs

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote#25]
We need to explain both the networking for a lab and for the cluster and its ingress in general as it stands with the external load balancer.

**Comment by Mierdin** [comment]
I'll close this in an upcoming PR but since the networking model is still something we have to settle on, I'm going to put a very light section in the docs for now. Once we decide to stick with a certain path (i.e. Multus vs NSM, I'll revisit this and invest time in documenting in more detail.
