### ISSUE TITLE
Document syringe-mock in Hacking on Syringe section

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote#69]
Would be nice to have bits of https://community.networkreliability.engineering/t/improving-antidote-web-developer-experience/171/7 integrated in the docs, for instance in https://antidoteproject.readthedocs.io/en/latest/hacking/platform.html#hacking-on-syringe

**Comment by Mierdin** [comment]
This is an *extremely* temporary solution that will be replaced very soon by the changes in MP1. These changes will allow us to start the API service with mocked data that's been placed into the API, and providing the same functionality that syringed-mock currently provides but in a much more exhaustive way. So at this point, I'd prefer that this not be in the docs - that forum post should suffice for now, for the few folks that really need to use it.
