### ISSUE TITLE
Create jinja templates lesson

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote#72]

**Comment by ShrutiVPawaskar** [comment]
## Introduction to Jinja2 and Junos PyEz 
### Part 1 – Intro to Jinja2
  Discusses Jijna2 syntax
*	Template rendering
*	{% if %}
*	{% for %}
*	{% set  %}  
  
### Part 2 – Into to PyEz
*	Connecting to a remote Junos device.
*	Getting configuration from the Junos device.
*	Loading configuration to the Junos device.  
  
### Part 3 –Configuring Junos Device using PyEz and Jinja2 Template
*	Creating Jinja2 template for Junos configuration.
*	Rendering Jinja2 template.
*	Pushing config to the Junos device using PyEz config module  
  
### Part 4 -	Optimizing Configuration Push
*	Use Junos PyEz inbuilt function to render Jinja2 template and  configure a single device 
with Config(dev, mode='private') as cu: 
            cu.load(template=template, template_vars=template_vars, format='text')  
  
### Part 5 –Configuring multiple Junos devices using Jinja2 template
*	Use a single Jinja2 template
*	Use YAML file or Python dictionary as variables
*	Pushing basic config like hostname to multiple devices.

**Comment by Mierdin** [comment]
@ShrutiVPawaskar This looks good, but I have one piece of important feedback. I'd like this seen split up into two lessons. Let's build a lesson totally focused on Jinja2, using the simplest possible software to illustrate examples. I'm thinking a little bit of YAML and Python to populate the templates, but the templates should be the focus. I'm thinking this would be a fundamentals lesson.

Separately from this, I'd like to see a lesson totally focused on PyEZ. It deserves its own lesson anyways, and putting it into the `configuration` course probably makes more sense at the moment.

Feel free to create a separate issue for the latter and write in the description that you're working on that as well.

**Comment by shahbhoomi** [comment]
@Mierdin we have simplified the jinja2 lesson to make it fundamental and focus more on jinja2 templating. The lessons are as below:
* **Part 1: Intro to Jinja2 (variable substitution)**  
* **Part 2 : For Loops in Jinja2**  
* **Part 3: If and Set statements in Jinja2**  
* **Part 4: Populating Jinja2 template with YAML**

**Comment by Mierdin** [comment]
Awesome, thank you!
