### ISSUE TITLE
Intro to Salt

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote#95]

**Comment by vinayak-skywalker** [comment]
Hi @Sudhishna and I are working on building this lesson. We've got a Saltstack container built on top of the ubuntu 16.04 docker image and here's the general outline of the stages:

Stage 1:  Part 1 - Salt Stack Master and Minion
Stage 2: Part 2 - Junos Proxy Minions
Stage 3: Part 3 - Executing Junos commands in Salt Stack
Stage 4: Part 4 - Pushing configuration onto Junos 
Stage5: Part 5 - Reactor System

Please let us know if this is okay.

Thanks!
Vinayak.

**Comment by vinayak-skywalker** [comment]
<img width="1659" alt="screen shot 2018-10-25 at 4 43 31 pm" src="https://user-images.githubusercontent.com/26114445/47532201-4b3f1a00-d875-11e8-82d1-d3f792c64992.png">

Hi @Mierdin , we are running into this above error when we spin up our container and lessons in NRE Labs. We created a new container and used it in the syringe.yml file https://hub.docker.com/r/vinayaks009/nre-saltstack/

But we're not able to access the terminal for our container from the webpage. Can you please help us here?

@Sudhishna
Thanks,
Vinayak.

**Comment by Mierdin** [comment]
Can you post your syringe logs?

**Comment by vinayak-skywalker** [comment]
Yes, here is a part where I find an error:

time="2018-10-25T21:37:35Z" level=debug msg="Received request for lesson definition: &{Working with SaltStack 19 false [0xc4203a9920] [0xc4203a98c0] [] [0xc42036f3e0] custom map[1:0xc4203a99e0 2:0xc4203a9a40 3:0xc4203a9aa0] introductory https://raw.githubusercontent.com/Sudhishna/nre-salt-2/master/lessons/lesson-19/lessondiagram.png }"
10.32.0.3 - - [25/Oct/2018:21:37:35 +0000] "GET /exp/lessondef/19 HTTP/1.1" 200 204
time="2018-10-25T21:37:35Z" level=debug msg="Scheduler received new request - &{0xc42015a900 2 8a68e470956234a50e0311c9661dfe26bd83841d74a78082f458073ee9ae5806 irtmsce2jdlibeb0 2}"
time="2018-10-25T21:37:35Z" level=info msg="Performing configuration of modified instance of lesson 19"
time="2018-10-25T21:37:35Z" level=error msg="Error creating InfluxDB UDP Client: lookup influxdb on 10.96.0.10:53: no such host"


I keep seeing this message after a while and it keeps repeating.

**Comment by Mierdin** [comment]
You can ignore the influxdb stuff. Can you post the full syringe logs?

**Comment by vinayak-skywalker** [comment]
[syringe-logs.txt](https://github.com/nre-learning/antidote/files/2517048/syringe-logs.txt)
Here is full Syringe logs. 
P.S: Thanks for replying so quickly!

**Comment by Mierdin** [comment]
You can ignore the influxdb stuff. Can you post the full syringe logs?

**Comment by Mierdin** [comment]
Hm. Looks okay to me. Maybe it's on the guac side. Can you get the antidote-web full logs too?

**Comment by cloudtoad** [comment]
The syringe yaml file in your repository is missing "ports: [22]" under the saltstack1 image, under utilities.  It needs to be there.

**Comment by Sudhishna** [comment]
@Mierdin @cloudtoad Thanks for your response. We terminated all the pods and ran the pods again, and we fixed this issue.

**Comment by Sudhishna** [comment]
@Mierdin @cloudtoad we are facing another issue though. 
**issue 1:**
we need to salt commands from root, but we are having issues running the saltstack1 linux machine as root. 

**issue 2:**
we manually started the master and minion from the guac. but the master and minion gets terminated receiving SIGTERM (automatically) . is this some issue that you know about ? 

Thanks for help.

--Sudhishna

**Comment by Mierdin** [comment]
Can you post a link to your branch so we can see your lesson definitions and docker files?

**Comment by Sudhishna** [comment]
Git Repo:
https://github.com/Sudhishna/antidote

lesson we've added is:
https://github.com/Sudhishna/antidote/tree/master/lessons/lesson-30

image we created for saltstack:
https://github.com/Sudhishna/antidote/tree/master/images/saltstack

**Comment by Mierdin** [comment]
Excellent. Could you please open a pull request and mark it with the [WIP] label, and we can discuss there?

**Comment by Mierdin** [comment]
Closed via #114
