### ISSUE TITLE
The list in antidote/lessons/lesson-14/stage1/list.yaml does not contain a list

### ISSUE THREAD

**Issue by pklimai** [nre-learning/antidote#98]
The "Introduction to YAML", Part 1 lesson is supposed to discuss lists, but the list.yaml file actually contains a dictionary (YAML mapping). It makes this lesson a bit misleading.

**Comment by Mierdin** [comment]
@pklimai Good catch! This was probably the result of some copypasta in the hurried rush to get things ready for release. I know this lesson went through a few changes, so it probably just got mixed up with the dict example.

Would you like to open a PR to convert these four items into a list (add `- ` before each)?

**Comment by pklimai** [comment]
Sure, will do!
