### ISSUE TITLE
Header change: add icons

### ISSUE THREAD

**Issue by jameskellynet** [nre-learning/antidote#99]
Let's add GitHub, Slack, and Twitter icons up top in the NRE Labs page header to encourage more eyes on the project and more Slack engagement.

**Comment by Mierdin** [comment]
@jameskellynet Can you re-open this in https://github.com/nre-learning/antidote-web

**Comment by jameskellynet** [comment]
Done

**Comment by Mierdin** [comment]
Moved to https://github.com/nre-learning/antidote-web/issues/15
